%YAML:1.0
---
aruco_bc_dict: ARUCO
aruco_bc_nmarkers: 80
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:800, corners:[ [ -400., -400., 0. ], [ -300., -400., 0. ], [
       -300., -500., 0. ], [ -400., -500., 0. ] ] }
   - { id:801, corners:[ [ -280., -400., 0. ], [ -180., -400., 0. ], [
       -180., -500., 0. ], [ -280., -500., 0. ] ] }
   - { id:802, corners:[ [ -160., -400., 0. ], [ -60., -400., 0. ], [
       -60., -500., 0. ], [ -160., -500., 0. ] ] }
   - { id:803, corners:[ [ -40., -400., 0. ], [ 60., -400., 0. ], [ 60.,
       -500., 0. ], [ -40., -500., 0. ] ] }
   - { id:804, corners:[ [ 80., -400., 0. ], [ 180., -400., 0. ], [ 180.,
       -500., 0. ], [ 80., -500., 0. ] ] }
   - { id:805, corners:[ [ 200., -400., 0. ], [ 300., -400., 0. ], [
       300., -500., 0. ], [ 200., -500., 0. ] ] }
   - { id:806, corners:[ [ 320., -400., 0. ], [ 420., -400., 0. ], [
       420., -500., 0. ], [ 320., -500., 0. ] ] }
   - { id:807, corners:[ [ 440., -400., 0. ], [ 540., -400., 0. ], [
       540., -500., 0. ], [ 440., -500., 0. ] ] }
   - { id:808, corners:[ [ -400., -280., 0. ], [ -300., -280., 0. ], [
       -300., -380., 0. ], [ -400., -380., 0. ] ] }
   - { id:809, corners:[ [ -280., -280., 0. ], [ -180., -280., 0. ], [
       -180., -380., 0. ], [ -280., -380., 0. ] ] }
   - { id:810, corners:[ [ -160., -280., 0. ], [ -60., -280., 0. ], [
       -60., -380., 0. ], [ -160., -380., 0. ] ] }
   - { id:811, corners:[ [ -40., -280., 0. ], [ 60., -280., 0. ], [ 60.,
       -380., 0. ], [ -40., -380., 0. ] ] }
   - { id:812, corners:[ [ 80., -280., 0. ], [ 180., -280., 0. ], [ 180.,
       -380., 0. ], [ 80., -380., 0. ] ] }
   - { id:813, corners:[ [ 200., -280., 0. ], [ 300., -280., 0. ], [
       300., -380., 0. ], [ 200., -380., 0. ] ] }
   - { id:814, corners:[ [ 320., -280., 0. ], [ 420., -280., 0. ], [
       420., -380., 0. ], [ 320., -380., 0. ] ] }
   - { id:815, corners:[ [ 440., -280., 0. ], [ 540., -280., 0. ], [
       540., -380., 0. ], [ 440., -380., 0. ] ] }
   - { id:816, corners:[ [ -400., -160., 0. ], [ -300., -160., 0. ], [
       -300., -260., 0. ], [ -400., -260., 0. ] ] }
   - { id:817, corners:[ [ -280., -160., 0. ], [ -180., -160., 0. ], [
       -180., -260., 0. ], [ -280., -260., 0. ] ] }
   - { id:818, corners:[ [ -160., -160., 0. ], [ -60., -160., 0. ], [
       -60., -260., 0. ], [ -160., -260., 0. ] ] }
   - { id:819, corners:[ [ -40., -160., 0. ], [ 60., -160., 0. ], [ 60.,
       -260., 0. ], [ -40., -260., 0. ] ] }
   - { id:820, corners:[ [ 80., -160., 0. ], [ 180., -160., 0. ], [ 180.,
       -260., 0. ], [ 80., -260., 0. ] ] }
   - { id:821, corners:[ [ 200., -160., 0. ], [ 300., -160., 0. ], [
       300., -260., 0. ], [ 200., -260., 0. ] ] }
   - { id:822, corners:[ [ 320., -160., 0. ], [ 420., -160., 0. ], [
       420., -260., 0. ], [ 320., -260., 0. ] ] }
   - { id:823, corners:[ [ 440., -160., 0. ], [ 540., -160., 0. ], [
       540., -260., 0. ], [ 440., -260., 0. ] ] }
   - { id:824, corners:[ [ -400., -40., 0. ], [ -300., -40., 0. ], [
       -300., -140., 0. ], [ -400., -140., 0. ] ] }
   - { id:825, corners:[ [ -280., -40., 0. ], [ -180., -40., 0. ], [
       -180., -140., 0. ], [ -280., -140., 0. ] ] }
   - { id:826, corners:[ [ -160., -40., 0. ], [ -60., -40., 0. ], [ -60.,
       -140., 0. ], [ -160., -140., 0. ] ] }
   - { id:827, corners:[ [ -40., -40., 0. ], [ 60., -40., 0. ], [ 60.,
       -140., 0. ], [ -40., -140., 0. ] ] }
   - { id:828, corners:[ [ 80., -40., 0. ], [ 180., -40., 0. ], [ 180.,
       -140., 0. ], [ 80., -140., 0. ] ] }
   - { id:829, corners:[ [ 200., -40., 0. ], [ 300., -40., 0. ], [ 300.,
       -140., 0. ], [ 200., -140., 0. ] ] }
   - { id:830, corners:[ [ 320., -40., 0. ], [ 420., -40., 0. ], [ 420.,
       -140., 0. ], [ 320., -140., 0. ] ] }
   - { id:831, corners:[ [ 440., -40., 0. ], [ 540., -40., 0. ], [ 540.,
       -140., 0. ], [ 440., -140., 0. ] ] }
   - { id:832, corners:[ [ -400., 80., 0. ], [ -300., 80., 0. ], [ -300.,
       -20., 0. ], [ -400., -20., 0. ] ] }
   - { id:833, corners:[ [ -280., 80., 0. ], [ -180., 80., 0. ], [ -180.,
       -20., 0. ], [ -280., -20., 0. ] ] }
   - { id:834, corners:[ [ -160., 80., 0. ], [ -60., 80., 0. ], [ -60.,
       -20., 0. ], [ -160., -20., 0. ] ] }
   - { id:835, corners:[ [ -40., 80., 0. ], [ 60., 80., 0. ], [ 60.,
       -20., 0. ], [ -40., -20., 0. ] ] }
   - { id:836, corners:[ [ 80., 80., 0. ], [ 180., 80., 0. ], [ 180.,
       -20., 0. ], [ 80., -20., 0. ] ] }
   - { id:837, corners:[ [ 200., 80., 0. ], [ 300., 80., 0. ], [ 300.,
       -20., 0. ], [ 200., -20., 0. ] ] }
   - { id:838, corners:[ [ 320., 80., 0. ], [ 420., 80., 0. ], [ 420.,
       -20., 0. ], [ 320., -20., 0. ] ] }
   - { id:839, corners:[ [ 440., 80., 0. ], [ 540., 80., 0. ], [ 540.,
       -20., 0. ], [ 440., -20., 0. ] ] }
   - { id:840, corners:[ [ -400., 200., 0. ], [ -300., 200., 0. ], [
       -300., 100., 0. ], [ -400., 100., 0. ] ] }
   - { id:841, corners:[ [ -280., 200., 0. ], [ -180., 200., 0. ], [
       -180., 100., 0. ], [ -280., 100., 0. ] ] }
   - { id:842, corners:[ [ -160., 200., 0. ], [ -60., 200., 0. ], [ -60.,
       100., 0. ], [ -160., 100., 0. ] ] }
   - { id:843, corners:[ [ -40., 200., 0. ], [ 60., 200., 0. ], [ 60.,
       100., 0. ], [ -40., 100., 0. ] ] }
   - { id:844, corners:[ [ 80., 200., 0. ], [ 180., 200., 0. ], [ 180.,
       100., 0. ], [ 80., 100., 0. ] ] }
   - { id:845, corners:[ [ 200., 200., 0. ], [ 300., 200., 0. ], [ 300.,
       100., 0. ], [ 200., 100., 0. ] ] }
   - { id:846, corners:[ [ 320., 200., 0. ], [ 420., 200., 0. ], [ 420.,
       100., 0. ], [ 320., 100., 0. ] ] }
   - { id:847, corners:[ [ 440., 200., 0. ], [ 540., 200., 0. ], [ 540.,
       100., 0. ], [ 440., 100., 0. ] ] }
   - { id:848, corners:[ [ -400., 320., 0. ], [ -300., 320., 0. ], [
       -300., 220., 0. ], [ -400., 220., 0. ] ] }
   - { id:849, corners:[ [ -280., 320., 0. ], [ -180., 320., 0. ], [
       -180., 220., 0. ], [ -280., 220., 0. ] ] }
   - { id:850, corners:[ [ -160., 320., 0. ], [ -60., 320., 0. ], [ -60.,
       220., 0. ], [ -160., 220., 0. ] ] }
   - { id:851, corners:[ [ -40., 320., 0. ], [ 60., 320., 0. ], [ 60.,
       220., 0. ], [ -40., 220., 0. ] ] }
   - { id:852, corners:[ [ 80., 320., 0. ], [ 180., 320., 0. ], [ 180.,
       220., 0. ], [ 80., 220., 0. ] ] }
   - { id:853, corners:[ [ 200., 320., 0. ], [ 300., 320., 0. ], [ 300.,
       220., 0. ], [ 200., 220., 0. ] ] }
   - { id:854, corners:[ [ 320., 320., 0. ], [ 420., 320., 0. ], [ 420.,
       220., 0. ], [ 320., 220., 0. ] ] }
   - { id:855, corners:[ [ 440., 320., 0. ], [ 540., 320., 0. ], [ 540.,
       220., 0. ], [ 440., 220., 0. ] ] }
   - { id:856, corners:[ [ -400., 440., 0. ], [ -300., 440., 0. ], [
       -300., 340., 0. ], [ -400., 340., 0. ] ] }
   - { id:857, corners:[ [ -280., 440., 0. ], [ -180., 440., 0. ], [
       -180., 340., 0. ], [ -280., 340., 0. ] ] }
   - { id:858, corners:[ [ -160., 440., 0. ], [ -60., 440., 0. ], [ -60.,
       340., 0. ], [ -160., 340., 0. ] ] }
   - { id:859, corners:[ [ -40., 440., 0. ], [ 60., 440., 0. ], [ 60.,
       340., 0. ], [ -40., 340., 0. ] ] }
   - { id:860, corners:[ [ 80., 440., 0. ], [ 180., 440., 0. ], [ 180.,
       340., 0. ], [ 80., 340., 0. ] ] }
   - { id:861, corners:[ [ 200., 440., 0. ], [ 300., 440., 0. ], [ 300.,
       340., 0. ], [ 200., 340., 0. ] ] }
   - { id:862, corners:[ [ 320., 440., 0. ], [ 420., 440., 0. ], [ 420.,
       340., 0. ], [ 320., 340., 0. ] ] }
   - { id:863, corners:[ [ 440., 440., 0. ], [ 540., 440., 0. ], [ 540.,
       340., 0. ], [ 440., 340., 0. ] ] }
   - { id:864, corners:[ [ -400., 560., 0. ], [ -300., 560., 0. ], [
       -300., 460., 0. ], [ -400., 460., 0. ] ] }
   - { id:865, corners:[ [ -280., 560., 0. ], [ -180., 560., 0. ], [
       -180., 460., 0. ], [ -280., 460., 0. ] ] }
   - { id:866, corners:[ [ -160., 560., 0. ], [ -60., 560., 0. ], [ -60.,
       460., 0. ], [ -160., 460., 0. ] ] }
   - { id:867, corners:[ [ -40., 560., 0. ], [ 60., 560., 0. ], [ 60.,
       460., 0. ], [ -40., 460., 0. ] ] }
   - { id:868, corners:[ [ 80., 560., 0. ], [ 180., 560., 0. ], [ 180.,
       460., 0. ], [ 80., 460., 0. ] ] }
   - { id:869, corners:[ [ 200., 560., 0. ], [ 300., 560., 0. ], [ 300.,
       460., 0. ], [ 200., 460., 0. ] ] }
   - { id:870, corners:[ [ 320., 560., 0. ], [ 420., 560., 0. ], [ 420.,
       460., 0. ], [ 320., 460., 0. ] ] }
   - { id:871, corners:[ [ 440., 560., 0. ], [ 540., 560., 0. ], [ 540.,
       460., 0. ], [ 440., 460., 0. ] ] }
   - { id:872, corners:[ [ -400., 680., 0. ], [ -300., 680., 0. ], [
       -300., 580., 0. ], [ -400., 580., 0. ] ] }
   - { id:873, corners:[ [ -280., 680., 0. ], [ -180., 680., 0. ], [
       -180., 580., 0. ], [ -280., 580., 0. ] ] }
   - { id:874, corners:[ [ -160., 680., 0. ], [ -60., 680., 0. ], [ -60.,
       580., 0. ], [ -160., 580., 0. ] ] }
   - { id:875, corners:[ [ -40., 680., 0. ], [ 60., 680., 0. ], [ 60.,
       580., 0. ], [ -40., 580., 0. ] ] }
   - { id:876, corners:[ [ 80., 680., 0. ], [ 180., 680., 0. ], [ 180.,
       580., 0. ], [ 80., 580., 0. ] ] }
   - { id:877, corners:[ [ 200., 680., 0. ], [ 300., 680., 0. ], [ 300.,
       580., 0. ], [ 200., 580., 0. ] ] }
   - { id:878, corners:[ [ 320., 680., 0. ], [ 420., 680., 0. ], [ 420.,
       580., 0. ], [ 320., 580., 0. ] ] }
   - { id:879, corners:[ [ 440., 680., 0. ], [ 540., 680., 0. ], [ 540.,
       580., 0. ], [ 440., 580., 0. ] ] }
