%YAML:1.0
---
aruco_bc_dict: ARUCO
aruco_bc_nmarkers: 80
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:720, corners:[ [ -400., -400., 0. ], [ -300., -400., 0. ], [
       -300., -500., 0. ], [ -400., -500., 0. ] ] }
   - { id:721, corners:[ [ -280., -400., 0. ], [ -180., -400., 0. ], [
       -180., -500., 0. ], [ -280., -500., 0. ] ] }
   - { id:722, corners:[ [ -160., -400., 0. ], [ -60., -400., 0. ], [
       -60., -500., 0. ], [ -160., -500., 0. ] ] }
   - { id:723, corners:[ [ -40., -400., 0. ], [ 60., -400., 0. ], [ 60.,
       -500., 0. ], [ -40., -500., 0. ] ] }
   - { id:724, corners:[ [ 80., -400., 0. ], [ 180., -400., 0. ], [ 180.,
       -500., 0. ], [ 80., -500., 0. ] ] }
   - { id:725, corners:[ [ 200., -400., 0. ], [ 300., -400., 0. ], [
       300., -500., 0. ], [ 200., -500., 0. ] ] }
   - { id:726, corners:[ [ 320., -400., 0. ], [ 420., -400., 0. ], [
       420., -500., 0. ], [ 320., -500., 0. ] ] }
   - { id:727, corners:[ [ 440., -400., 0. ], [ 540., -400., 0. ], [
       540., -500., 0. ], [ 440., -500., 0. ] ] }
   - { id:728, corners:[ [ -400., -280., 0. ], [ -300., -280., 0. ], [
       -300., -380., 0. ], [ -400., -380., 0. ] ] }
   - { id:729, corners:[ [ -280., -280., 0. ], [ -180., -280., 0. ], [
       -180., -380., 0. ], [ -280., -380., 0. ] ] }
   - { id:730, corners:[ [ -160., -280., 0. ], [ -60., -280., 0. ], [
       -60., -380., 0. ], [ -160., -380., 0. ] ] }
   - { id:731, corners:[ [ -40., -280., 0. ], [ 60., -280., 0. ], [ 60.,
       -380., 0. ], [ -40., -380., 0. ] ] }
   - { id:732, corners:[ [ 80., -280., 0. ], [ 180., -280., 0. ], [ 180.,
       -380., 0. ], [ 80., -380., 0. ] ] }
   - { id:733, corners:[ [ 200., -280., 0. ], [ 300., -280., 0. ], [
       300., -380., 0. ], [ 200., -380., 0. ] ] }
   - { id:734, corners:[ [ 320., -280., 0. ], [ 420., -280., 0. ], [
       420., -380., 0. ], [ 320., -380., 0. ] ] }
   - { id:735, corners:[ [ 440., -280., 0. ], [ 540., -280., 0. ], [
       540., -380., 0. ], [ 440., -380., 0. ] ] }
   - { id:736, corners:[ [ -400., -160., 0. ], [ -300., -160., 0. ], [
       -300., -260., 0. ], [ -400., -260., 0. ] ] }
   - { id:737, corners:[ [ -280., -160., 0. ], [ -180., -160., 0. ], [
       -180., -260., 0. ], [ -280., -260., 0. ] ] }
   - { id:738, corners:[ [ -160., -160., 0. ], [ -60., -160., 0. ], [
       -60., -260., 0. ], [ -160., -260., 0. ] ] }
   - { id:739, corners:[ [ -40., -160., 0. ], [ 60., -160., 0. ], [ 60.,
       -260., 0. ], [ -40., -260., 0. ] ] }
   - { id:740, corners:[ [ 80., -160., 0. ], [ 180., -160., 0. ], [ 180.,
       -260., 0. ], [ 80., -260., 0. ] ] }
   - { id:741, corners:[ [ 200., -160., 0. ], [ 300., -160., 0. ], [
       300., -260., 0. ], [ 200., -260., 0. ] ] }
   - { id:742, corners:[ [ 320., -160., 0. ], [ 420., -160., 0. ], [
       420., -260., 0. ], [ 320., -260., 0. ] ] }
   - { id:743, corners:[ [ 440., -160., 0. ], [ 540., -160., 0. ], [
       540., -260., 0. ], [ 440., -260., 0. ] ] }
   - { id:744, corners:[ [ -400., -40., 0. ], [ -300., -40., 0. ], [
       -300., -140., 0. ], [ -400., -140., 0. ] ] }
   - { id:745, corners:[ [ -280., -40., 0. ], [ -180., -40., 0. ], [
       -180., -140., 0. ], [ -280., -140., 0. ] ] }
   - { id:746, corners:[ [ -160., -40., 0. ], [ -60., -40., 0. ], [ -60.,
       -140., 0. ], [ -160., -140., 0. ] ] }
   - { id:747, corners:[ [ -40., -40., 0. ], [ 60., -40., 0. ], [ 60.,
       -140., 0. ], [ -40., -140., 0. ] ] }
   - { id:748, corners:[ [ 80., -40., 0. ], [ 180., -40., 0. ], [ 180.,
       -140., 0. ], [ 80., -140., 0. ] ] }
   - { id:749, corners:[ [ 200., -40., 0. ], [ 300., -40., 0. ], [ 300.,
       -140., 0. ], [ 200., -140., 0. ] ] }
   - { id:750, corners:[ [ 320., -40., 0. ], [ 420., -40., 0. ], [ 420.,
       -140., 0. ], [ 320., -140., 0. ] ] }
   - { id:751, corners:[ [ 440., -40., 0. ], [ 540., -40., 0. ], [ 540.,
       -140., 0. ], [ 440., -140., 0. ] ] }
   - { id:752, corners:[ [ -400., 80., 0. ], [ -300., 80., 0. ], [ -300.,
       -20., 0. ], [ -400., -20., 0. ] ] }
   - { id:753, corners:[ [ -280., 80., 0. ], [ -180., 80., 0. ], [ -180.,
       -20., 0. ], [ -280., -20., 0. ] ] }
   - { id:754, corners:[ [ -160., 80., 0. ], [ -60., 80., 0. ], [ -60.,
       -20., 0. ], [ -160., -20., 0. ] ] }
   - { id:755, corners:[ [ -40., 80., 0. ], [ 60., 80., 0. ], [ 60.,
       -20., 0. ], [ -40., -20., 0. ] ] }
   - { id:756, corners:[ [ 80., 80., 0. ], [ 180., 80., 0. ], [ 180.,
       -20., 0. ], [ 80., -20., 0. ] ] }
   - { id:757, corners:[ [ 200., 80., 0. ], [ 300., 80., 0. ], [ 300.,
       -20., 0. ], [ 200., -20., 0. ] ] }
   - { id:758, corners:[ [ 320., 80., 0. ], [ 420., 80., 0. ], [ 420.,
       -20., 0. ], [ 320., -20., 0. ] ] }
   - { id:759, corners:[ [ 440., 80., 0. ], [ 540., 80., 0. ], [ 540.,
       -20., 0. ], [ 440., -20., 0. ] ] }
   - { id:760, corners:[ [ -400., 200., 0. ], [ -300., 200., 0. ], [
       -300., 100., 0. ], [ -400., 100., 0. ] ] }
   - { id:761, corners:[ [ -280., 200., 0. ], [ -180., 200., 0. ], [
       -180., 100., 0. ], [ -280., 100., 0. ] ] }
   - { id:762, corners:[ [ -160., 200., 0. ], [ -60., 200., 0. ], [ -60.,
       100., 0. ], [ -160., 100., 0. ] ] }
   - { id:763, corners:[ [ -40., 200., 0. ], [ 60., 200., 0. ], [ 60.,
       100., 0. ], [ -40., 100., 0. ] ] }
   - { id:764, corners:[ [ 80., 200., 0. ], [ 180., 200., 0. ], [ 180.,
       100., 0. ], [ 80., 100., 0. ] ] }
   - { id:765, corners:[ [ 200., 200., 0. ], [ 300., 200., 0. ], [ 300.,
       100., 0. ], [ 200., 100., 0. ] ] }
   - { id:766, corners:[ [ 320., 200., 0. ], [ 420., 200., 0. ], [ 420.,
       100., 0. ], [ 320., 100., 0. ] ] }
   - { id:767, corners:[ [ 440., 200., 0. ], [ 540., 200., 0. ], [ 540.,
       100., 0. ], [ 440., 100., 0. ] ] }
   - { id:768, corners:[ [ -400., 320., 0. ], [ -300., 320., 0. ], [
       -300., 220., 0. ], [ -400., 220., 0. ] ] }
   - { id:769, corners:[ [ -280., 320., 0. ], [ -180., 320., 0. ], [
       -180., 220., 0. ], [ -280., 220., 0. ] ] }
   - { id:770, corners:[ [ -160., 320., 0. ], [ -60., 320., 0. ], [ -60.,
       220., 0. ], [ -160., 220., 0. ] ] }
   - { id:771, corners:[ [ -40., 320., 0. ], [ 60., 320., 0. ], [ 60.,
       220., 0. ], [ -40., 220., 0. ] ] }
   - { id:772, corners:[ [ 80., 320., 0. ], [ 180., 320., 0. ], [ 180.,
       220., 0. ], [ 80., 220., 0. ] ] }
   - { id:773, corners:[ [ 200., 320., 0. ], [ 300., 320., 0. ], [ 300.,
       220., 0. ], [ 200., 220., 0. ] ] }
   - { id:774, corners:[ [ 320., 320., 0. ], [ 420., 320., 0. ], [ 420.,
       220., 0. ], [ 320., 220., 0. ] ] }
   - { id:775, corners:[ [ 440., 320., 0. ], [ 540., 320., 0. ], [ 540.,
       220., 0. ], [ 440., 220., 0. ] ] }
   - { id:776, corners:[ [ -400., 440., 0. ], [ -300., 440., 0. ], [
       -300., 340., 0. ], [ -400., 340., 0. ] ] }
   - { id:777, corners:[ [ -280., 440., 0. ], [ -180., 440., 0. ], [
       -180., 340., 0. ], [ -280., 340., 0. ] ] }
   - { id:778, corners:[ [ -160., 440., 0. ], [ -60., 440., 0. ], [ -60.,
       340., 0. ], [ -160., 340., 0. ] ] }
   - { id:779, corners:[ [ -40., 440., 0. ], [ 60., 440., 0. ], [ 60.,
       340., 0. ], [ -40., 340., 0. ] ] }
   - { id:780, corners:[ [ 80., 440., 0. ], [ 180., 440., 0. ], [ 180.,
       340., 0. ], [ 80., 340., 0. ] ] }
   - { id:781, corners:[ [ 200., 440., 0. ], [ 300., 440., 0. ], [ 300.,
       340., 0. ], [ 200., 340., 0. ] ] }
   - { id:782, corners:[ [ 320., 440., 0. ], [ 420., 440., 0. ], [ 420.,
       340., 0. ], [ 320., 340., 0. ] ] }
   - { id:783, corners:[ [ 440., 440., 0. ], [ 540., 440., 0. ], [ 540.,
       340., 0. ], [ 440., 340., 0. ] ] }
   - { id:784, corners:[ [ -400., 560., 0. ], [ -300., 560., 0. ], [
       -300., 460., 0. ], [ -400., 460., 0. ] ] }
   - { id:785, corners:[ [ -280., 560., 0. ], [ -180., 560., 0. ], [
       -180., 460., 0. ], [ -280., 460., 0. ] ] }
   - { id:786, corners:[ [ -160., 560., 0. ], [ -60., 560., 0. ], [ -60.,
       460., 0. ], [ -160., 460., 0. ] ] }
   - { id:787, corners:[ [ -40., 560., 0. ], [ 60., 560., 0. ], [ 60.,
       460., 0. ], [ -40., 460., 0. ] ] }
   - { id:788, corners:[ [ 80., 560., 0. ], [ 180., 560., 0. ], [ 180.,
       460., 0. ], [ 80., 460., 0. ] ] }
   - { id:789, corners:[ [ 200., 560., 0. ], [ 300., 560., 0. ], [ 300.,
       460., 0. ], [ 200., 460., 0. ] ] }
   - { id:790, corners:[ [ 320., 560., 0. ], [ 420., 560., 0. ], [ 420.,
       460., 0. ], [ 320., 460., 0. ] ] }
   - { id:791, corners:[ [ 440., 560., 0. ], [ 540., 560., 0. ], [ 540.,
       460., 0. ], [ 440., 460., 0. ] ] }
   - { id:792, corners:[ [ -400., 680., 0. ], [ -300., 680., 0. ], [
       -300., 580., 0. ], [ -400., 580., 0. ] ] }
   - { id:793, corners:[ [ -280., 680., 0. ], [ -180., 680., 0. ], [
       -180., 580., 0. ], [ -280., 580., 0. ] ] }
   - { id:794, corners:[ [ -160., 680., 0. ], [ -60., 680., 0. ], [ -60.,
       580., 0. ], [ -160., 580., 0. ] ] }
   - { id:795, corners:[ [ -40., 680., 0. ], [ 60., 680., 0. ], [ 60.,
       580., 0. ], [ -40., 580., 0. ] ] }
   - { id:796, corners:[ [ 80., 680., 0. ], [ 180., 680., 0. ], [ 180.,
       580., 0. ], [ 80., 580., 0. ] ] }
   - { id:797, corners:[ [ 200., 680., 0. ], [ 300., 680., 0. ], [ 300.,
       580., 0. ], [ 200., 580., 0. ] ] }
   - { id:798, corners:[ [ 320., 680., 0. ], [ 420., 680., 0. ], [ 420.,
       580., 0. ], [ 320., 580., 0. ] ] }
   - { id:799, corners:[ [ 440., 680., 0. ], [ 540., 680., 0. ], [ 540.,
       580., 0. ], [ 440., 580., 0. ] ] }
